FROM webui:1.9.4

USER webui

RUN set -x \
        && export HTTP_PROXY="http://x.x.x.x:1080" \           # 添加此项 
        && export HTTPS_PROXY="http://x.x.x.x:1080" \          # 添加此项
        && export NO_PROXY="localhost,127.0.0.1" \             # 添加此项
        && cd /home/webui/stable-diffusion-webui \
        && sed 's/start()/#start()/g' launch.py -i \
        && cd extensions \
        && git clone https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN.git \
        && git clone https://github.com/hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans.git \
        && git clone https://github.com/Physton/sd-webui-prompt-all-in-one.git \
        && git clone https://github.com/thisjam/sd-webui-oldsix-prompt.git \
        && git clone https://github.com/Mikubill/sd-webui-controlnet.git \
        && git clone https://github.com/Bing-su/adetailer.git \
        && git clone https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git \
        && git clone https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git \
        && git clone https://github.com/picobyte/stable-diffusion-webui-wd14-tagger.git \
        && git clone https://github.com/s0md3v/sd-webui-roop.git \
        && git clone https://github.com/Uminosachi/sd-webui-inpaint-anything.git \
        && git clone https://github.com/continue-revolution/sd-webui-segment-anything.git \
        && git clone https://github.com/pkuliyi2015/sd-webui-stablesr.git \
        && git clone https://github.com/fkunn1326/openpose-editor.git \
        && git clone https://github.com/kohya-ss/sd-webui-additional-networks.git \
        && . ~/stable-diffusion-webui/venv/bin/activate \
        && cd /home/webui/stable-diffusion-webui \
        && bash webui.sh --skip-torch-cuda-test --enable-insecure-extension-access \
        && pip install basicsr llama_cpp_python \
        && bash webui.sh --skip-torch-cuda-test --enable-insecure-extension-access \
        && sed 's/#start()/start()/g' launch.py -i 

EXPOSE 7860

WORKDIR /home/webui

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sleep", "infinity"]

