FROM anaconda3:2023.03-1

COPY torch/torch-2.1.2+cu121-cp310-cp310-linux_x86_64.whl /tmp          # 注意：torch 对应版本从 modules/launch_utils.py 代码中获取

USER webui

RUN set -x \
        && export HTTP_PROXY="http://x.x.x.x:1080" \                    # 添加此项
        && export HTTPS_PROXY="http://x.x.x.x:1080" \                   # 添加此项
        && export NO_PROXY="localhost,127.0.0.1" \                      # 添加此项
        && cd ~ \
        && . anaconda3/etc/profile.d/conda.sh \
        && conda activate \
        && git clone -b v1.9.4 --depth=1 https://github.com/AUTOMATIC1111/stable-diffusion-webui.git \      # 注意版本为：v1.9.4
        && cd stable-diffusion-webui \
        && mkdir -p outputs \
        && sed 's/start()/#start()/g' launch.py -i \
        && python -m venv venv \
        && . venv/bin/activate \
        && echo ". ~/stable-diffusion-webui/venv/bin/activate" >> ~/.bashrc \
        && pip install --upgrade pip \
        && pip install /tmp/torch-2.1.2+cu121-cp310-cp310-linux_x86_64.whl \
        && bash webui.sh --skip-torch-cuda-test \
        && pip install -U -I --no-deps xformers==0.0.23.post1 --prefer-binary \         # 注：xformers==0.0.23.post1 从 cat modules/launch_utils.py | grep 'xformers' 命令中获取
        && sed 's/#start()/start()/g' launch.py -i \
        && echo "#!/bin/bash" >> start.sh \
        && echo "exec ./webui.sh --xformers --listen --skip-version-check --enable-insecure-extension-access --theme=dark" >> start.sh \
        && chmod 755 start.sh 

EXPOSE 7860

WORKDIR /home/webui

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sleep", "infinity"]

